name: TWS CI WORKFLOW

on:
    push:
jobs:
    build: #job name
        runs-on: ubuntu-latest #OS
        steps:
            - name:Checkout Code
                uses: actions/checkout@v4 # clone the code into ubuntu runner
            - name: Setup Docker
                uses: docker/setup-buildx-action@v4 # setup docker in ubuntu runner
        